<?php
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/feature_helpers.php';
if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? '') !== 'admin') {
    header('Location: ' . BASE_URL . '/login.php');
    exit;
}

require_once __DIR__ . '/vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;

$db = getDB();
$revenue = (float)$db->query("SELECT COALESCE(SUM(total),0) FROM orders")->fetch_row()[0];
$orders = (int)$db->query("SELECT COUNT(*) FROM orders")->fetch_row()[0];
$users = (int)$db->query("SELECT COUNT(*) FROM users")->fetch_row()[0];
$products = (int)$db->query("SELECT COUNT(*) FROM products")->fetch_row()[0];
$doctors = (int)$db->query("SELECT COUNT(*) FROM doctors")->fetch_row()[0];

$today = date('d M Y');
$html = <<<HTML
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family: 'DejaVu Sans', sans-serif; padding: 30px; color: #1a1a1a;">
<h1 style="color: #005221; border-bottom: 2px solid #005221; padding-bottom: 10px;">Ayurviro — Reports</h1>
<p style="color: #666; margin-bottom: 30px;">Generated on {$today}</p>

<h2 style="color: #005221;">Overview</h2>
<table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
    <tr><td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Total Revenue</td><td style="padding: 10px; border: 1px solid #ddd;">₹{$revenue}</td></tr>
    <tr><td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Total Orders</td><td style="padding: 10px; border: 1px solid #ddd;">{$orders}</td></tr>
    <tr><td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Total Users</td><td style="padding: 10px; border: 1px solid #ddd;">{$users}</td></tr>
    <tr><td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Total Products</td><td style="padding: 10px; border: 1px solid #ddd;">{$products}</td></tr>
    <tr><td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">Total Doctors</td><td style="padding: 10px; border: 1px solid #ddd;">{$doctors}</td></tr>
</table>

<p style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; text-align: center;">Generated by Ayurviro — Ancient Wisdom for Modern Living</p>
</body>
</html>
HTML;

$options = new Options();
$options->set('isRemoteEnabled', false);
$options->set('isHtml5ParserEnabled', true);
$options->set('defaultFont', 'DejaVu Sans');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('ayurviro-report-' . date('Y-m-d') . '.pdf', ['Attachment' => true]);
