<?php
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/feature_helpers.php';
require_login();

require_once __DIR__ . '/vendor/autoload.php';
use Dompdf\Dompdf;
use Dompdf\Options;

$db = getDB();
$uid = (int)$_SESSION['user_id'];
$user = current_user($db);

$records = [];
if (table_exists($db, 'health_records')) {
    $stmt = $db->prepare('SELECT * FROM health_records WHERE user_id = ? ORDER BY record_date DESC, created_at DESC');
    $stmt->bind_param('i', $uid);
    $stmt->execute();
    $records = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
}

$metrics = [];
if (table_exists($db, 'patient_metrics')) {
    $stmt = $db->prepare('SELECT * FROM patient_metrics WHERE user_id = ? ORDER BY record_date DESC LIMIT 20');
    $stmt->bind_param('i', $uid);
    $stmt->execute();
    $metrics = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
}

$metrics_rows = '';
foreach ($metrics as $m) {
    $metrics_rows .= '<tr>
        <td style="padding: 8px; border: 1px solid #ddd;">' . h($m['record_date']) . '</td>
        <td style="padding: 8px; border: 1px solid #ddd;">' . h(($m['bp_systolic'] ?? '-') . '/' . ($m['bp_diastolic'] ?? '-')) . '</td>
        <td style="padding: 8px; border: 1px solid #ddd;">' . h($m['weight'] ?? '-') . ' kg</td>
        <td style="padding: 8px; border: 1px solid #ddd;">' . h($m['blood_sugar'] ?? '-') . '</td>
    </tr>';
}

$records_list = '';
foreach ($records as $r) {
    $records_list .= '<li style="padding: 6px 0;">' . h($r['title'] ?: $r['file_name'] ?? 'Record') . ' — ' . h($r['record_type'] ?? 'General') . ' (' . h($r['record_date']) . ')</li>';
}

$name = h($user['full_name'] ?? 'User');
$email = h($user['email'] ?? '');
$today = date('d M Y');

$html = <<<HTML
<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"></head>
<body style="font-family: 'DejaVu Sans', sans-serif; padding: 30px; color: #1a1a1a;">
<h1 style="color: #005221; border-bottom: 2px solid #005221; padding-bottom: 10px;">Health Records — {$name}</h1>
<p style="color: #666; margin-bottom: 30px;">{$email} · Generated on {$today}</p>

<h2 style="color: #005221;">Vitals History</h2>
<table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
    <thead>
        <tr style="background: #005221; color: white;">
            <th style="padding: 8px; border: 1px solid #005221; text-align: left;">Date</th>
            <th style="padding: 8px; border: 1px solid #005221; text-align: left;">BP</th>
            <th style="padding: 8px; border: 1px solid #005221; text-align: left;">Weight</th>
            <th style="padding: 8px; border: 1px solid #005221; text-align: left;">Sugar</th>
        </tr>
    </thead>
    <tbody>
        {$metrics_rows}
    </tbody>
</table>

<h2 style="color: #005221;">Health Files</h2>
<ul style="padding-left: 20px;">{$records_list}</ul>

<p style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; text-align: center;">Generated by AyurViora — Ancient Wisdom for Modern Living</p>
</body>
</html>
HTML;

$options = new Options();
$options->set('isRemoteEnabled', false);
$options->set('isHtml5ParserEnabled', true);
$options->set('defaultFont', 'DejaVu Sans');

$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('health-records-' . $user['full_name'] . '.pdf', ['Attachment' => true]);

