<?php require_once __DIR__ . '/includes/config.php'; require_once __DIR__ . '/includes/feature_helpers.php'; require_login(); $site_title='Retailer Reports'; require_once __DIR__ . '/includes/header.php'; ?>
<section class="pt-32 pb-section-gap px-margin-mobile md:px-margin-desktop max-w-container-max mx-auto">
<div class="mb-8"><h1 class="font-display-lg text-display-lg text-primary">Sales Reports</h1><p class="text-on-surface-variant">Sales trends, top products, revenue and margins.</p></div>
<div class="mb-6 flex flex-wrap gap-2"><?php foreach(['Today','This Week','This Month','This Quarter','This Year','Custom Range'] as $t): ?><button class="rounded-full border border-outline-variant px-4 py-2 first:bg-primary first:text-on-primary"><?= $t ?></button><?php endforeach; ?></div>
<div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><?= stat_card('payments','Total Sales','₹1,25,000','↑8.5%') ?><?= stat_card('receipt_long','Total Orders','84','↑12%') ?><?= stat_card('shopping_bag','Avg Order Value','₹1,488','↓2%') ?><?= stat_card('show_chart','Profit Margin','22.4%','↑1.2%') ?></div>
<div class="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><section class="rounded-xl border border-outline-variant bg-surface-container-lowest p-6"><h2 class="font-headline-md text-headline-md text-primary">Sales Trend</h2><div class="mt-6 flex h-72 items-end gap-3 border-b border-l border-outline-variant p-4"><?php foreach([30,45,35,70,55,85,75,95,88,110] as $v): ?><div class="flex-1 rounded-t bg-primary" style="height:<?= $v ?>%"></div><?php endforeach; ?></div></section><section class="rounded-xl border border-outline-variant bg-surface-container-lowest p-6"><h2 class="font-headline-md text-headline-md text-primary">Category Breakdown</h2><div class="mx-auto mt-6 h-44 w-44 rounded-full" style="background:conic-gradient(#005221 0 30%,#D4AF37 30% 55%,#10B981 55% 75%,#EF4444 75% 90%,#B7E4C7 90% 100%)"></div><p class="mt-4 text-on-surface-variant">Churnas 30%, Oils 25%, Tablets 20%, Syrups 15%.</p></section></div>
<div class="mt-8 rounded-xl border border-outline-variant bg-surface-container-lowest p-6"><h2 class="font-headline-md text-headline-md text-primary">Export</h2><div class="mt-4 flex flex-wrap gap-3"><a href="export-report-pdf.php" class="rounded-lg border border-outline-variant px-4 py-2 inline-block">Export as PDF</a><button class="rounded-lg border border-outline-variant px-4 py-2">Export as CSV</button><button class="rounded-lg border border-outline-variant px-4 py-2">Export as Excel</button><label class="flex items-center gap-2"><input type="checkbox" class="rounded text-primary"> Send monthly report to my email</label></div></div>
</section>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
