<?php
require_once __DIR__ . '/includes/config.php';
require_once __DIR__ . '/includes/feature_helpers.php';
require_login();
$db=getDB(); $site_title='Retailer Stock'; $products=fetch_products($db, 16);
require_once __DIR__ . '/includes/header.php';
?>
<section class="pt-32 pb-section-gap px-margin-mobile md:px-margin-desktop max-w-container-max mx-auto">
<div class="mb-8"><h1 class="font-display-lg text-display-lg text-primary">Stock Management</h1><p class="text-on-surface-variant">Track inventory, reorder levels and stock movements.</p></div>
<div class="mb-6 grid gap-3 md:grid-cols-4"><input class="rounded-lg border-outline-variant" placeholder="Search product, SKU, category"><select class="rounded-lg border-outline-variant"><option>All Categories</option></select><select class="rounded-lg border-outline-variant"><option>All Stock</option><option>Low Stock</option><option>Out of Stock</option></select><button onclick="downloadInventory()" class="rounded-lg border border-primary px-4 text-primary">Download Inventory Report</button></div>
<div class="rounded-xl border border-outline-variant bg-surface-container-lowest overflow-hidden"><table class="w-full min-w-[760px] text-left"><thead class="bg-surface-container text-label-sm uppercase text-on-surface-variant"><tr><th class="p-4">Image</th><th class="p-4">Product</th><th class="p-4">SKU</th><th class="p-4">Current Stock</th><th class="p-4">Reorder Level</th><th class="p-4">Status</th><th class="p-4">Actions</th></tr></thead><tbody class="divide-y divide-outline-variant"><?php foreach ($products as $p): $stock=(int)($p['stock']??0); ?><tr><td class="p-4"><img class="h-12 w-12 rounded-lg object-cover" src="<?= h($p['image_url'] ?: 'assets/uploads/logo.jpeg') ?>"></td><td class="p-4"><?= h($p['name']) ?></td><td class="p-4">SKU-<?= (int)$p['id'] ?></td><td class="p-4 font-bold"><?= $stock ?></td><td class="p-4"><input class="w-20 rounded border-outline-variant" value="10"></td><td class="p-4"><span class="<?= $stock<=0?'bg-error-container text-error':($stock<=10?'bg-tertiary-fixed':'bg-primary-fixed text-primary') ?> rounded-full px-3 py-1 text-label-sm"><?= $stock<=0?'Out of Stock':($stock<=10?'Low Stock':'In Stock') ?></span></td><td class="p-4 flex gap-2"><button data-adjust class="text-primary">Adjust</button><a href="<?= BASE_URL ?>/order-punch.php" class="text-primary">Reorder</a></td></tr><?php endforeach; ?></tbody></table></div>
</section>
<div id="stock-modal" class="fixed inset-0 z-[60] hidden items-center justify-center bg-black/40 p-4"><div class="w-full max-w-md rounded-xl bg-surface-container-lowest p-6"><h3 class="font-headline-md text-headline-md text-primary">Adjust Stock</h3><select class="mt-4 w-full rounded-lg border-outline-variant"><option>Add Stock</option><option>Remove Stock</option></select><input class="mt-4 w-full rounded-lg border-outline-variant" type="number" placeholder="Quantity"><textarea class="mt-4 w-full rounded-lg border-outline-variant" placeholder="Reason"></textarea><button onclick="document.getElementById('stock-modal').classList.add('hidden')" class="mt-4 w-full rounded-lg bg-primary py-3 text-on-primary">Save Adjustment</button></div></div>
<script>document.querySelectorAll('[data-adjust]').forEach(b=>b.addEventListener('click',()=>{const m=document.getElementById('stock-modal');m.classList.remove('hidden');m.classList.add('flex')}));function downloadInventory(){const a=document.createElement('a');a.href='data:text/csv,Product,Stock%0ASample,10';a.download='inventory.csv';a.click();}</script>
<?php require_once __DIR__ . '/includes/footer.php'; ?>
