<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/feature_helpers.php';
if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? '') !== 'admin') { header('Location: ' . BASE_URL . '/login.php'); exit; }
$db=getDB(); $page_title='Coupons & Offers'; $active_page='coupons';
$coupons=[]; if(table_exists($db,'coupons')){ $res=$db->query('SELECT * FROM coupons ORDER BY created_at DESC'); $coupons=$res?$res->fetch_all(MYSQLI_ASSOC):[]; }
require_once __DIR__ . '/includes/head.php';
?>
<body class="bg-surface font-body-md text-on-surface flex min-h-screen"><?php require_once __DIR__ . '/includes/sidebar.php'; ?>
<main class="flex-grow ml-64 p-margin-desktop bg-surface min-h-screen">
<header class="mb-10 flex justify-between items-end"><div><h1 class="text-display-lg font-display-lg text-primary">Coupons & Offers</h1><p class="text-on-surface-variant">Create and manage promotional campaigns.</p></div><button class="rounded-lg bg-primary px-5 py-3 text-on-primary" onclick="document.getElementById('coupon-form').classList.toggle('hidden')">Create Coupon</button></header>
<section class="mb-8 grid gap-4 md:grid-cols-3"><?php foreach(['Monsoon Sale — 25% off all Churnas','New User Offer — ₹100 off first order','Free Delivery — Orders above ₹500'] as $campaign): ?><div class="rounded-xl border border-outline-variant bg-surface-container-lowest p-5"><h2 class="text-title-lg text-primary"><?= h($campaign) ?></h2><p class="text-on-surface-variant">Active campaign · ends soon</p><button class="mt-4 text-primary">View</button></div><?php endforeach; ?></section>
<div class="mb-6 flex gap-2"><?php foreach(['All','Active','Scheduled','Expired','Disabled'] as $tab): ?><button class="rounded-full border border-outline-variant px-4 py-2 first:bg-primary first:text-on-primary"><?= $tab ?></button><?php endforeach; ?></div>
<section class="rounded-xl border border-outline-variant bg-surface-container-lowest overflow-hidden"><table class="w-full text-left"><thead class="bg-surface-container text-label-sm uppercase text-on-surface-variant"><tr><th class="p-4">Code</th><th class="p-4">Type</th><th class="p-4">Value</th><th class="p-4">Min Order</th><th class="p-4">Usage</th><th class="p-4">Valid Till</th><th class="p-4">Status</th><th class="p-4">Actions</th></tr></thead><tbody class="divide-y divide-outline-variant"><?php foreach($coupons ?: [['code'=>'WELCOME10','type'=>'percent','value'=>10,'min_order_amount'=>299,'used_count'=>45,'usage_limit'=>100,'valid_to'=>date('Y-m-d',strtotime('+30 days')),'active'=>1]] as $c): ?><tr><td class="p-4 font-bold"><?= h($c['code']) ?></td><td class="p-4"><?= h($c['type']) ?></td><td class="p-4"><?= h($c['value']) ?></td><td class="p-4"><?= money($c['min_order_amount']) ?></td><td class="p-4"><?= (int)$c['used_count'] ?> / <?= (int)$c['usage_limit'] ?></td><td class="p-4"><?= h($c['valid_to']) ?></td><td class="p-4"><span class="rounded-full bg-primary-fixed px-3 py-1 text-primary"><?= !empty($c['active'])?'Active':'Disabled' ?></span></td><td class="p-4"><button class="text-primary">Edit</button></td></tr><?php endforeach; ?></tbody></table></section>
<section id="coupon-form" class="hidden mt-8 rounded-xl border border-outline-variant bg-surface-container-lowest p-6"><h2 class="text-headline-md text-primary">Create/Edit Coupon</h2><div class="mt-4 grid gap-4 md:grid-cols-3"><input class="rounded-lg border-outline-variant" placeholder="Coupon Code"><select class="rounded-lg border-outline-variant"><option>Percentage</option><option>Flat Amount</option><option>Free Shipping</option></select><input class="rounded-lg border-outline-variant" placeholder="Value"><input class="rounded-lg border-outline-variant" placeholder="Min Order"><input class="rounded-lg border-outline-variant" placeholder="Usage Limit"><input type="date" class="rounded-lg border-outline-variant"></div><button class="mt-5 rounded-lg bg-primary px-5 py-3 text-on-primary">Save</button></section>
</main></body></html>
