<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/feature_helpers.php';
if (!isset($_SESSION['user_id']) || ($_SESSION['role'] ?? '') !== 'admin') { header('Location: ' . BASE_URL . '/login.php'); exit; }
$db=getDB(); $page_title='Reports'; $active_page='reports';
$revenue=0;$orders=0;$users=0; try{$revenue=(float)$db->query("SELECT COALESCE(SUM(total),0) FROM orders")->fetch_row()[0];$orders=(int)$db->query("SELECT COUNT(*) FROM orders")->fetch_row()[0];$users=(int)$db->query("SELECT COUNT(*) FROM users")->fetch_row()[0];}catch(Exception $e){error_log($e->getMessage());}
require_once __DIR__ . '/includes/head.php';
?>
<body class="bg-surface font-body-md text-on-surface flex min-h-screen"><?php require_once __DIR__ . '/includes/sidebar.php'; ?>
<main class="flex-grow ml-64 p-margin-desktop bg-surface min-h-screen">
<header class="mb-10"><h1 class="text-display-lg font-display-lg text-primary">Reports & Analytics</h1><p class="text-on-surface-variant">Revenue, users, products, doctors, orders and returns analytics.</p></header>
<div class="mb-6 flex flex-wrap gap-2"><?php foreach(['Overview','Revenue','Users','Products','Doctors','Orders','Returns'] as $tab): ?><button class="rounded-full border border-outline-variant px-4 py-2 first:bg-primary first:text-on-primary"><?= $tab ?></button><?php endforeach; ?></div>
<div class="mb-8 flex flex-wrap gap-2"><?php foreach(['Today','This Week','This Month','Last Month','This Quarter','This Year','All Time'] as $range): ?><button class="rounded-lg border border-outline-variant px-4 py-2"><?= $range ?></button><?php endforeach; ?><label class="flex items-center gap-2"><input type="checkbox" class="rounded text-primary"> Compare to previous period</label></div>
<section class="grid gap-4 md:grid-cols-3 xl:grid-cols-6 mb-8"><?= stat_card('payments','Total Revenue',money($revenue),'') ?><?= stat_card('receipt_long','Total Orders',(string)$orders,'') ?><?= stat_card('group','Total Users',(string)$users,'') ?><?= stat_card('shopping_cart','Average Order Value',money($orders?$revenue/$orders:0),'') ?><?= stat_card('ads_click','Conversion Rate','4.8%','') ?><?= stat_card('repeat','Repeat Purchase','32%','') ?></section>
<section class="grid gap-6 xl:grid-cols-[1fr_360px]"><div class="rounded-xl border border-outline-variant bg-surface-container-lowest p-6"><h2 class="text-headline-md text-primary">Revenue Trend</h2><div class="mt-6 flex h-80 items-end gap-3 border-b border-l border-outline-variant p-4"><?php foreach([20,35,42,58,65,80,74,95,100,88,112,130] as $v): ?><div class="flex-1 rounded-t bg-primary" style="height:<?= $v/1.3 ?>%"></div><?php endforeach; ?></div></div><div class="rounded-xl border border-outline-variant bg-surface-container-lowest p-6"><h2 class="text-headline-md text-primary">Orders Fulfillment</h2><div class="mx-auto mt-8 h-48 w-48 rounded-full" style="background:conic-gradient(#005221 0 60%,#3B82F6 60% 78%,#F59E0B 78% 90%,#EF4444 90% 100%)"></div><p class="mt-5 text-on-surface-variant">Delivered, processing, returned and cancelled split.</p></div></section>
<section class="mt-8 rounded-xl border border-outline-variant bg-surface-container-lowest p-6"><h2 class="text-headline-md text-primary">Export Section</h2><div class="mt-4 flex flex-wrap gap-3"><a href="export-report-pdf.php" class="rounded-lg bg-primary px-5 py-3 text-on-primary inline-block">Download PDF</a><button class="rounded-lg border border-outline-variant px-5 py-3">CSV</button><button class="rounded-lg border border-outline-variant px-5 py-3">Excel</button><input class="rounded-lg border-outline-variant" placeholder="Schedule recipient emails"></div></section>
</main></body></html>
